version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: bootcamp-app
    ports:
      - "3000:3000"
    env_file:
      - backend/.env
    volumes:
      - ./backend/src/config/serviceAccountKey.json:/app/src/config/serviceAccountKey.json:ro
